version: '2'
services:
    nginx:
        build: ./images/nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./images/nginx/conf.d:/etc/nginx/conf.d
            - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
    php:
        build: ./images/php
        links:
            - mysql
            - redis
        volumes:
            - ./www:/var/www
            - ./images/php/conf.d:/usr/local/etc/php/conf.d/
    mysql:
        build: ./images/mysql
        ports:
            - "3307:3306"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./images/mysql/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    redis:
        build: ./images/redis
        volumes:
          - ./images/redis/redis.conf:/usr/local/etc/redis/redis.conf
