version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
    php:
        build: ./images/php
        links:
            - mysql
        volumes:
            - ./www:/var/www
            - ./images/php/conf.d:/usr/local/etc/php/conf.d/
    mysql:
        build: ./images/mysql
        ports:
            - "3306:3307"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./images/mysql/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
